/*==============================================================================
  Autolabel Module - Master Test Suite

  Purpose: Run all autolabel tests sequentially with pass/fail tracking
  Author: Jeffrey Clark

  Test Files:
    1. dofiles/02_basic_workflow.do - Variable & value labels eng/swe
    2. dofiles/03_verification_scenarios.do - File/metadata verification
    3. dofiles/04_caching.do - 24-hour last_checked caching
    4. dofiles/05_offline_mode.do - Online vs offline validation
    5. dofiles/16_dataset_updates_test.do - Dataset update checks
    6. dofiles/20_scope_drill.do - Depth-agnostic scope browse (SCB depth=2)
    7. dofiles/22_comprehensive.do - Full end-to-end test
    8. dofiles/25_depth_agnostic.do - DST depth=1 + apostrophe-insensitive match
    9. dofiles/30_update_notification.do - Update detection & notification
    10. dofiles/99_cleanup.do - Clean state restoration

  Usage:
    From repo root: do stata/tests/run_all_tests.do

  Requirements:
    - API server running (localhost:5000 for dev, or production)
    - .project-root file in repo root
    - Sibling registream repo (or set global CORE_SRC before running)
==============================================================================*/

clear all
version 16.0

*==============================================================================
* Find project root
*==============================================================================

local cwd = "`c(pwd)'"
local project_root ""

forvalues i = 0/5 {
	local search_path = "`cwd'"
	forvalues j = 1/`i' {
		local search_path = "`search_path'/.."
	}

	capture confirm file "`search_path'/.project-root"
	if _rc == 0 {
		quietly cd "`search_path'"
		local project_root = "`c(pwd)'"
		quietly cd "`cwd'"
		continue, break
	}
}

if "`project_root'" == "" {
	di as error "ERROR: Could not find .project-root file"
	exit 601
}

global PROJECT_ROOT "`project_root'"
global TEST_DIR "$PROJECT_ROOT/stata/tests"
global SRC_DIR "$PROJECT_ROOT/stata/src"
global TEST_LOGS_DIR "$TEST_DIR/logs"
global LISA_DATA "$PROJECT_ROOT/examples/lisa.dta"

* Registream core — sibling repo, one level up from autolabel
global CORE_SRC "$PROJECT_ROOT/../registream/stata/src"

* Create directories
cap mkdir "$TEST_LOGS_DIR"

* Dual adopath: autolabel source + registream core
discard
adopath ++ "$SRC_DIR"

capture confirm file "$CORE_SRC/registream.ado"
if _rc != 0 {
	di as error "ERROR: registream core not found at $CORE_SRC"
	di as error "Set global CORE_SRC to registream/stata/src before running."
	exit 601
}
adopath ++ "$CORE_SRC"
do "$CORE_SRC/_rs_utils.ado"
cap do "$CORE_SRC/../dev/host_override.do"
do "$CORE_SRC/../dev/auto_approve.do"

*==============================================================================
* Display test suite info
*==============================================================================

di as result ""
di as result "============================================================"
di as result "Autolabel Module - Master Test Suite"
di as result "============================================================"
di as result ""
di as text "Project root:     $PROJECT_ROOT"
di as text "Test directory:   $TEST_DIR"
di as text "Source directory:  $SRC_DIR"
di as text "Core source:      `core_src'"
di as text ""

*==============================================================================
* Verify example data exists
*==============================================================================

cap confirm file "$PROJECT_ROOT/examples/lisa.dta"
if (_rc != 0) {
	di as error "ERROR: examples/lisa.dta not found"
	di as error "This test data is generated by the datamirror module."
	exit 601
}
di as text "Using example data: $PROJECT_ROOT/examples/lisa.dta"
di as text ""

*==============================================================================
* Track test results
*==============================================================================

local tests_total = 0
local tests_passed = 0
local tests_failed = 0

*==============================================================================
* Run each test sequentially
*==============================================================================

* Test 1: Basic Workflow
di as result "============================================================"
di as result "Test 1/11: Basic Workflow (02)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/02_basic_workflow.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 1"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 1 (rc=`=_rc')"
}

* Test 2: Verification Scenarios
di as result ""
di as result "============================================================"
di as result "Test 2/11: Verification Scenarios (03)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/03_verification_scenarios.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 2"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 2 (rc=`=_rc')"
}

* Test 3: Caching
di as result ""
di as result "============================================================"
di as result "Test 3/11: 24-Hour Timestamp Caching (04)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/04_caching.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 3"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 3 (rc=`=_rc')"
}

* Test 4: Offline Mode
di as result ""
di as result "============================================================"
di as result "Test 4/11: Online vs Offline Validation (05)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/05_offline_mode.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 4"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 4 (rc=`=_rc')"
}

* Test 5: Dataset Updates
di as result ""
di as result "============================================================"
di as result "Test 5/11: Dataset Update Checks (16)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/16_dataset_updates_test.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 5"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 5 (rc=`=_rc')"
}

* Test 6: Scope drill (depth-agnostic, SCB depth=2)
di as result ""
di as result "============================================================"
di as result "Test 6/11: Scope drill (20)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/20_scope_drill.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 6"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 6 (rc=`=_rc')"
}

* Test 7: Comprehensive
di as result ""
di as result "============================================================"
di as result "Test 7/11: Comprehensive Suite (22)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/22_comprehensive.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 7"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 7 (rc=`=_rc')"
}

* Test 8: Depth-agnostic (DST depth=1)
di as result ""
di as result "============================================================"
di as result "Test 8/11: Depth-agnostic (25)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/25_depth_agnostic.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 8"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 8 (rc=`=_rc')"
}

* Test 9: Update & Notification System
di as result ""
di as result "============================================================"
di as result "Test 9/11: Update & Notification System (30)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/30_update_notification.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 9"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 9 (rc=`=_rc')"
}

* Test 10: rclass returns across subcommands
di as result ""
di as result "============================================================"
di as result "Test 10/11: rclass returns (26)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/26_rclass_returns.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 10"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 10 (rc=`=_rc')"
}

* Test 11: Cleanup
di as result ""
di as result "============================================================"
di as result "Test 11/11: Clean State Restoration (99)"
di as result "============================================================"
local ++tests_total
cap noi do "$TEST_DIR/dofiles/99_cleanup.do"
if (_rc == 0) {
	local ++tests_passed
	di as result "[PASS] Test 11"
}
else {
	local ++tests_failed
	di as error "[FAIL] Test 11 (rc=`=_rc')"
}

*==============================================================================
* Final Summary
*==============================================================================

di as result ""
di as result "============================================================"
di as result "Test Suite Summary"
di as result "============================================================"
di as result ""

local pass_rate = round((`tests_passed' / `tests_total') * 100)

di as result "Total Tests:  `tests_total'"
di as result "Passed:       {result:`tests_passed'}"
if (`tests_failed' > 0) {
	di as error "Failed:       {error:`tests_failed'}"
}
else {
	di as result "Failed:       `tests_failed'"
}
di as result "Pass Rate:    `pass_rate'%"
di as result ""

if (`tests_failed' == 0) {
	di as result "============================================================"
	di as result "[SUCCESS] ALL TESTS PASSED!"
	di as result "============================================================"
	di as result ""
}
else {
	di as error "============================================================"
	di as error "[FAILURE] SOME TESTS FAILED"
	di as error "============================================================"
	di as error ""
	di as text "Check individual test output above for details."
	di as text "Logs directory: $TEST_LOGS_DIR"
	di as text ""
}

* Exit with error if any tests failed
if (`tests_failed' > 0) {
	exit 1
}
