# Generated by registream/tools/render_citations.py -- DO NOT EDIT BY HAND.
#
# Edit registream/citations.yaml, then run
#   python tools/render_citations.py write-r
# from the registream/ repo root.

.CITATION_WORK_KEY    <- "autolabel"
.CITATION_TITLE       <- "autolabel: Automating variable and value labeling for register-data research"
.CITATION_SHORT_TITLE <- "Automating variable and value labeling"
.CITATION_URL         <- "https://registream.org/docs/autolabel"
.CITATION_YEAR        <- "2024\u2013"
.CITATION_BIBTEX_KEY  <- "clark2024autolabel"
.CITATION_AUTHORS_APA <- "Clark, J. & Wen, J."

.CITATION_APA                      <- "Clark, J. & Wen, J. (2024\u2013). autolabel: Automating variable and value labeling for register-data research. https://registream.org/docs/autolabel"
.CITATION_APA_VERSIONED_TEMPLATE   <- "Clark, J. & Wen, J. (2024\u2013). autolabel: Automating variable and value labeling for register-data research (Version %s). Available at: https://registream.org/docs/autolabel."
.CITATION_BIBTEX_PLAIN             <- "@software{clark2024autolabel,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{autolabel: Automating variable and value labeling for register-data research}},\n  year    = {2024--},\n  url     = {https://registream.org/docs/autolabel}\n}"
.CITATION_BIBTEX_VERSIONED_TEMPLATE <- "@software{clark2024autolabel,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{autolabel: Automating variable and value labeling for register-data research}},\n  version = {{{VERSION}}},\n  year    = {2024--},\n  url     = {https://registream.org/docs/autolabel}\n}"
