"""Generated by registream/tools/render_citations.py. DO NOT EDIT BY HAND.

Edit registream/citations.yaml, then run `python tools/render_citations.py write-python`.
"""

from __future__ import annotations

WORK_KEY = 'autolabel'
TITLE = 'autolabel: Automating variable and value labeling for register-data research'
SHORT_TITLE = 'Automating variable and value labeling'
URL = 'https://registream.org/docs/autolabel'
YEAR = '2024–'
BIBTEX_KEY = 'clark2024autolabel'
AUTHORS_APA = 'Clark, J. & Wen, J.'

APA = 'Clark, J. & Wen, J. (2024–). autolabel: Automating variable and value labeling for register-data research. https://registream.org/docs/autolabel'
APA_VERSIONED_TEMPLATE = 'Clark, J. & Wen, J. (2024–). autolabel: Automating variable and value labeling for register-data research (Version {version}). Available at: https://registream.org/docs/autolabel.'
BIBTEX_PLAIN = '@software{clark2024autolabel,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{autolabel: Automating variable and value labeling for register-data research}},\n  year    = {2024--},\n  url     = {https://registream.org/docs/autolabel}\n}'
BIBTEX_VERSIONED_TEMPLATE = '@software{clark2024autolabel,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{autolabel: Automating variable and value labeling for register-data research}},\n  version = {{{VERSION}}},\n  year    = {2024--},\n  url     = {https://registream.org/docs/autolabel}\n}'
